[podsync] Build updated image
k8s-at-home/container-images pull request #84
Opened 2021-04-05 11:14 UTC by Marx2

**Description of the change**

Build podsync image with newest youtube-dl
Play nice with Kubernetes deployment

- fixes #83

2021-04-05 22:58 UTC, onedr0p requested changes

2021-04-05 22:58 UTC, onedr0p commented on apps/podsync/Dockerfile
> +    python3-pip \
You don't need python3-pip, check this out

https://github.com/wernight/docker-youtube-dl/blob/6f39bcc1119edb0fa1a21f58f0e12b1005f72be9/Dockerfile#L16

all you need is python3

2021-04-05 22:58 UTC, onedr0p commented on apps/podsync/Dockerfile
> +
You'll need to set the targetplatform and version args here too or else the won't be used in this stage.

2021-04-05 23:09 UTC, onedr0p requested changes

2021-04-05 23:09 UTC, onedr0p commented on apps/podsync/Dockerfile
> +ARG VERSION
You don't need these in this part of the stage

2021-04-05 23:11 UTC, onedr0p requested changes

2021-04-05 23:11 UTC, onedr0p commented on apps/podsync/Dockerfile
> +    GO111MODULE=off
Probably need this set to on

2021-04-05 23:19 UTC, james-d-elliott requested changes

2021-04-05 23:19 UTC, james-d-elliott commented on apps/podsync/Dockerfile
> +  && go build -o /bin/podsync ./cmd/podsync
```suggestion
  && git checkout ${VERSION} \
  && go mod download \
  && go build -o /bin/podsync ./cmd/podsync
```

2021-04-05 23:19 UTC, onedr0p requested changes

2021-04-05 23:19 UTC, onedr0p commented on apps/podsync/Dockerfile
> +  && \
You should also symlink python3 to python

e.g. `ln -s /usr/bin/python3 /usr/bin/python`

2021-04-06 06:19 UTC, Marx2 commented on apps/podsync/Dockerfile
> +    python3-pip \
I've changed method of installing youtube-dl from apt package to pip package (python package delivers freshiest version). Without pip image building fails:
`#11 38.18 /bin/sh: 1: pip3: not found`

2021-04-06 06:22 UTC, Marx2 commented on apps/podsync/Dockerfile
> +  && \
I'll add it, but why do I you think I need it? I don't call python directly

2021-04-06 06:23 UTC, Marx2 commented on apps/podsync/Dockerfile
> +    GO111MODULE=off
this was crucial change to make libraries working

2021-04-06 07:01 UTC, Marx2 commented on apps/podsync/Dockerfile
> +  && go build -o /bin/podsync ./cmd/podsync
seems not to be needed (after enabling GO111MODULE=on)

2021-04-06 08:38 UTC, bjw-s requested changes

2021-04-06 08:38 UTC, bjw-s commented on apps/podsync/PLATFORM
> +linux/amd64,linux/arm64
Missing newline

2021-04-06 08:38 UTC, bjw-s commented on apps/podsync/VERSION
> +v2.4.0
Missing newline

2021-04-06 08:48 UTC, bjw-s requested changes

2021-04-06 08:48 UTC, bjw-s commented on apps/podsync/entrypoint.sh
> +exec /app/podsync ${EXTRA_ARGS}
Missing newline

2021-04-06 10:10 UTC, onedr0p commented on apps/podsync/Dockerfile
> +    python3-pip \
That's not what I'm asking...

2021-04-06 10:40 UTC, onedr0p commented on apps/podsync/Dockerfile
> +    python3-pip \
Take a look at that Dockerfile I linked, that is how you should be installing ytdl.

2021-04-06 14:07 UTC, onedr0p commented on apps/podsync/Dockerfile
> +  && wget -O /usr/bin/youtube-dl https://github.com/ytdl-org/youtube-dl/releases/latest/download/youtube-dl \
Use curl, not wget

2021-04-06 14:34 UTC, merged